export interface BibleCharacter {
  id: string;
  name: string;
  emoji: string;
  title: string;
  period: string;
  summary: string;
  keyVerse: string;
  keyVerseRef: string;
  lessons: string[];
  books: string[];
}

export const bibleCharacters: BibleCharacter[] = [
  {
    id: 'moses',
    name: 'Moisés',
    emoji: '🔥',
    title: 'O Libertador',
    period: 'Antigo Testamento',
    summary: 'Moisés foi escolhido por Deus para libertar o povo de Israel da escravidão no Egito. Mesmo com suas inseguranças, Deus o usou poderosamente para realizar milagres, receber os Dez Mandamentos e guiar o povo pelo deserto por 40 anos.',
    keyVerse: 'Não temas; está quieto e vê o livramento do Senhor.',
    keyVerseRef: 'Êxodo 14:13',
    lessons: ['Deus usa pessoas imperfeitas', 'A obediência traz libertação', 'A fé supera o medo'],
    books: ['Êxodo', 'Levítico', 'Números', 'Deuteronômio'],
  },
  {
    id: 'david',
    name: 'Davi',
    emoji: '👑',
    title: 'O Homem Segundo o Coração de Deus',
    period: 'Antigo Testamento',
    summary: 'De pastor de ovelhas a rei de Israel, Davi é um dos personagens mais complexos da Bíblia. Guerreiro, poeta, pecador e adorador — sua vida mostra que Deus olha o coração e que o arrependimento sincero restaura.',
    keyVerse: 'O Senhor é o meu pastor; nada me faltará.',
    keyVerseRef: 'Salmos 23:1',
    lessons: ['Deus vê o coração', 'A adoração é poderosa', 'O arrependimento traz restauração'],
    books: ['1 Samuel', '2 Samuel', 'Salmos'],
  },
  {
    id: 'maria',
    name: 'Maria',
    emoji: '🕊️',
    title: 'A Mãe de Jesus',
    period: 'Novo Testamento',
    summary: 'Maria, uma jovem humilde de Nazaré, foi escolhida para ser a mãe do Salvador. Sua fé inabalável e disposição para dizer "sim" a Deus, mesmo sem entender completamente, é um exemplo de rendição total.',
    keyVerse: 'Eis aqui a serva do Senhor; cumpra-se em mim segundo a tua palavra.',
    keyVerseRef: 'Lucas 1:38',
    lessons: ['Humildade atrai a graça de Deus', 'Fé é dizer sim mesmo sem entender', 'Deus escolhe os humildes'],
    books: ['Mateus', 'Lucas', 'João', 'Atos'],
  },
  {
    id: 'paul',
    name: 'Paulo',
    emoji: '⚡',
    title: 'O Apóstolo dos Gentios',
    period: 'Novo Testamento',
    summary: 'De perseguidor dos cristãos a maior missionário da história, Paulo teve uma transformação radical no caminho de Damasco. Escreveu grande parte do Novo Testamento e plantou igrejas por todo o mundo conhecido.',
    keyVerse: 'Tudo posso naquele que me fortalece.',
    keyVerseRef: 'Filipenses 4:13',
    lessons: ['Deus transforma qualquer pessoa', 'A graça é suficiente', 'Perseverança na missão'],
    books: ['Romanos', 'Coríntios', 'Gálatas', 'Efésios', 'Filipenses'],
  },
  {
    id: 'abraham',
    name: 'Abraão',
    emoji: '⭐',
    title: 'O Pai da Fé',
    period: 'Antigo Testamento',
    summary: 'Abraão é considerado o pai da fé. Deus o chamou para deixar tudo e seguir para uma terra desconhecida, prometendo que dele sairia uma grande nação. Sua fé foi testada muitas vezes, mas ele confiou em Deus.',
    keyVerse: 'Abraão creu no Senhor, e isso lhe foi imputado como justiça.',
    keyVerseRef: 'Gênesis 15:6',
    lessons: ['A fé exige ação', 'Deus cumpre suas promessas', 'A espera faz parte do plano de Deus'],
    books: ['Gênesis'],
  },
  {
    id: 'joseph',
    name: 'José',
    emoji: '🌈',
    title: 'O Sonhador',
    period: 'Antigo Testamento',
    summary: 'Vendido como escravo pelos próprios irmãos, José passou por prisão e sofrimento, mas nunca abandonou sua fé. Deus o exaltou até se tornar governador do Egito, salvando nações da fome.',
    keyVerse: 'Vós bem intentastes mal contra mim; porém Deus o intentou para bem.',
    keyVerseRef: 'Gênesis 50:20',
    lessons: ['Deus tem um propósito no sofrimento', 'A integridade é recompensada', 'Perdão liberta'],
    books: ['Gênesis'],
  },
  {
    id: 'esther',
    name: 'Ester',
    emoji: '💎',
    title: 'A Rainha Corajosa',
    period: 'Antigo Testamento',
    summary: 'Ester, uma jovem judia que se tornou rainha da Pérsia, arriscou sua vida para salvar seu povo do extermínio. Sua coragem e fé mostram que Deus nos posiciona para momentos decisivos.',
    keyVerse: 'Quem sabe se não foi para um tempo como este que chegaste a ser rainha?',
    keyVerseRef: 'Ester 4:14',
    lessons: ['Coragem em tempos de crise', 'Deus posiciona estrategicamente', 'Jejum e oração precedem vitórias'],
    books: ['Ester'],
  },
  {
    id: 'daniel',
    name: 'Daniel',
    emoji: '🦁',
    title: 'O Fiel na Adversidade',
    period: 'Antigo Testamento',
    summary: 'Levado cativo para Babilônia ainda jovem, Daniel manteve sua fé firme mesmo em terra estranha. Deus o livrou da cova dos leões e lhe revelou mistérios sobre o futuro.',
    keyVerse: 'O meu Deus enviou o seu anjo e fechou a boca dos leões.',
    keyVerseRef: 'Daniel 6:22',
    lessons: ['Fidelidade mesmo sob pressão', 'Deus protege os seus', 'Oração é inegociável'],
    books: ['Daniel'],
  },
  {
    id: 'peter',
    name: 'Pedro',
    emoji: '🪨',
    title: 'A Rocha',
    period: 'Novo Testamento',
    summary: 'Pedro, um pescador impetuoso, foi transformado no líder da igreja primitiva. Apesar de suas falhas — incluindo negar Jesus três vezes — ele foi restaurado e se tornou uma coluna da fé.',
    keyVerse: 'Tu és o Cristo, o Filho do Deus vivo.',
    keyVerseRef: 'Mateus 16:16',
    lessons: ['Restauração após a queda', 'Coragem nasce da fé', 'Deus usa quem está disposto'],
    books: ['Mateus', 'Marcos', 'Lucas', 'Atos', '1 Pedro', '2 Pedro'],
  },
  {
    id: 'ruth',
    name: 'Rute',
    emoji: '🌾',
    title: 'A Leal',
    period: 'Antigo Testamento',
    summary: 'Rute, uma moabita viúva, escolheu permanecer ao lado de sua sogra Noemi e seguir o Deus de Israel. Sua lealdade e trabalho foram recompensados — ela se tornou bisavó do rei Davi.',
    keyVerse: 'Aonde quer que fores, irei eu; e onde quer que pousares, ali pousarei eu.',
    keyVerseRef: 'Rute 1:16',
    lessons: ['Lealdade é uma virtude rara', 'Deus honra a fidelidade', 'Recomeçar é possível com Deus'],
    books: ['Rute'],
  },
];
