export type QuizDifficulty = 'facil' | 'medio' | 'dificil';
export type QuizCategory = 'antigo_testamento' | 'novo_testamento' | 'personagens' | 'versiculos' | 'parabolas' | 'profetas';

export interface QuizQuestion {
  id: string;
  question: string;
  options: string[];
  correctIndex: number;
  category: QuizCategory;
  difficulty: QuizDifficulty;
  explanation: string;
  reference: string;
}

export interface QuizCategoryInfo {
  id: QuizCategory;
  title: string;
  emoji: string;
  color: string;
}

export const quizCategories: QuizCategoryInfo[] = [
  { id: 'antigo_testamento', title: 'Antigo Testamento', emoji: '📜', color: '#8B4513' },
  { id: 'novo_testamento', title: 'Novo Testamento', emoji: '✝️', color: '#2d6a4f' },
  { id: 'personagens', title: 'Personagens', emoji: '👤', color: '#1a365d' },
  { id: 'versiculos', title: 'Versículos', emoji: '📖', color: '#6b21a8' },
  { id: 'parabolas', title: 'Parábolas', emoji: '🌾', color: '#b45309' },
  { id: 'profetas', title: 'Profetas', emoji: '🔥', color: '#991b1b' },
];

export const bibleQuizQuestions: QuizQuestion[] = [
  {
    id: 'q1',
    question: 'Quem construiu a arca a mando de Deus?',
    options: ['Abraão', 'Noé', 'Moisés', 'Davi'],
    correctIndex: 1,
    category: 'antigo_testamento',
    difficulty: 'facil',
    explanation: 'Deus ordenou a Noé que construísse uma arca para salvar sua família e os animais do dilúvio.',
    reference: 'Gênesis 6:14',
  },
  {
    id: 'q2',
    question: 'Quantos dias Jesus ficou no deserto sendo tentado?',
    options: ['7 dias', '30 dias', '40 dias', '12 dias'],
    correctIndex: 2,
    category: 'novo_testamento',
    difficulty: 'facil',
    explanation: 'Jesus jejuou 40 dias e 40 noites no deserto antes de ser tentado pelo diabo.',
    reference: 'Mateus 4:1-2',
  },
  {
    id: 'q3',
    question: 'Quem foi lançado na cova dos leões?',
    options: ['Elias', 'Daniel', 'Jonas', 'Sansão'],
    correctIndex: 1,
    category: 'personagens',
    difficulty: 'facil',
    explanation: 'Daniel foi lançado na cova dos leões por orar ao Deus verdadeiro, mas Deus fechou a boca dos leões.',
    reference: 'Daniel 6:16',
  },
  {
    id: 'q4',
    question: 'Complete: "Porque Deus amou o mundo de tal maneira que deu o seu..."',
    options: ['Anjo mais forte', 'Profeta mais sábio', 'Filho unigênito', 'Espírito Santo'],
    correctIndex: 2,
    category: 'versiculos',
    difficulty: 'facil',
    explanation: 'João 3:16 é um dos versículos mais conhecidos da Bíblia, falando do amor de Deus pela humanidade.',
    reference: 'João 3:16',
  },
  {
    id: 'q5',
    question: 'Na parábola do Filho Pródigo, o que o filho pediu ao pai?',
    options: ['Um cavalo', 'A herança antecipada', 'Uma casa', 'Permissão para viajar'],
    correctIndex: 1,
    category: 'parabolas',
    difficulty: 'facil',
    explanation: 'O filho mais novo pediu ao pai sua parte da herança e foi gastar em uma terra distante.',
    reference: 'Lucas 15:12',
  },
  {
    id: 'q6',
    question: 'Qual profeta foi engolido por um grande peixe?',
    options: ['Elias', 'Isaías', 'Jonas', 'Jeremias'],
    correctIndex: 2,
    category: 'profetas',
    difficulty: 'facil',
    explanation: 'Jonas desobedeceu a Deus e fugiu, sendo engolido por um grande peixe por 3 dias.',
    reference: 'Jonas 1:17',
  },
  {
    id: 'q7',
    question: 'Qual o primeiro livro da Bíblia?',
    options: ['Êxodo', 'Salmos', 'Gênesis', 'Mateus'],
    correctIndex: 2,
    category: 'antigo_testamento',
    difficulty: 'facil',
    explanation: 'Gênesis é o primeiro livro da Bíblia e conta a história da criação do mundo.',
    reference: 'Gênesis 1:1',
  },
  {
    id: 'q8',
    question: 'Quem batizou Jesus no rio Jordão?',
    options: ['Pedro', 'João Batista', 'Paulo', 'Tiago'],
    correctIndex: 1,
    category: 'novo_testamento',
    difficulty: 'facil',
    explanation: 'João Batista batizou Jesus no rio Jordão e o Espírito Santo desceu como pomba.',
    reference: 'Mateus 3:13-16',
  },
  {
    id: 'q9',
    question: 'Quantos livros tem a Bíblia?',
    options: ['55', '66', '72', '60'],
    correctIndex: 1,
    category: 'antigo_testamento',
    difficulty: 'medio',
    explanation: 'A Bíblia tem 66 livros: 39 no Antigo Testamento e 27 no Novo Testamento.',
    reference: 'Bíblia Sagrada',
  },
  {
    id: 'q10',
    question: 'Quem derrotou o gigante Golias?',
    options: ['Saul', 'Josué', 'Davi', 'Sansão'],
    correctIndex: 2,
    category: 'personagens',
    difficulty: 'facil',
    explanation: 'Davi, ainda jovem pastor, derrotou o gigante filisteu Golias com uma funda e uma pedra.',
    reference: '1 Samuel 17:50',
  },
  {
    id: 'q11',
    question: 'Na parábola do Semeador, o que representa a semente?',
    options: ['O dinheiro', 'A Palavra de Deus', 'As boas obras', 'A fé'],
    correctIndex: 1,
    category: 'parabolas',
    difficulty: 'medio',
    explanation: 'Jesus explicou que a semente representa a Palavra de Deus semeada nos corações.',
    reference: 'Lucas 8:11',
  },
  {
    id: 'q12',
    question: 'Qual profeta desafiou os profetas de Baal no monte Carmelo?',
    options: ['Eliseu', 'Elias', 'Isaías', 'Amós'],
    correctIndex: 1,
    category: 'profetas',
    difficulty: 'medio',
    explanation: 'Elias desafiou 450 profetas de Baal e Deus respondeu com fogo do céu.',
    reference: '1 Reis 18:38',
  },
  {
    id: 'q13',
    question: 'Complete: "O Senhor é o meu pastor..."',
    options: ['...nada me faltará', '...me guiará', '...me protegerá', '...estará comigo'],
    correctIndex: 0,
    category: 'versiculos',
    difficulty: 'facil',
    explanation: 'O Salmo 23 é um dos mais amados da Bíblia, escrito pelo rei Davi.',
    reference: 'Salmos 23:1',
  },
  {
    id: 'q14',
    question: 'Quantos apóstolos Jesus escolheu?',
    options: ['7', '10', '12', '15'],
    correctIndex: 2,
    category: 'novo_testamento',
    difficulty: 'facil',
    explanation: 'Jesus escolheu 12 apóstolos para serem seus discípulos mais próximos.',
    reference: 'Lucas 6:13',
  },
  {
    id: 'q15',
    question: 'Quem foi o primeiro homem criado por Deus?',
    options: ['Noé', 'Abraão', 'Adão', 'Moisés'],
    correctIndex: 2,
    category: 'personagens',
    difficulty: 'facil',
    explanation: 'Adão foi o primeiro homem, criado por Deus do pó da terra.',
    reference: 'Gênesis 2:7',
  },
  {
    id: 'q16',
    question: 'Qual é o maior mandamento segundo Jesus?',
    options: ['Não matarás', 'Amar a Deus sobre todas as coisas', 'Honrar pai e mãe', 'Não cobiçarás'],
    correctIndex: 1,
    category: 'novo_testamento',
    difficulty: 'medio',
    explanation: 'Jesus disse que o maior mandamento é amar a Deus de todo coração, alma e entendimento.',
    reference: 'Mateus 22:37',
  },
  {
    id: 'q17',
    question: 'Quantos frutos do Espírito Santo são mencionados em Gálatas?',
    options: ['7', '9', '10', '12'],
    correctIndex: 1,
    category: 'versiculos',
    difficulty: 'medio',
    explanation: 'Os 9 frutos são: amor, alegria, paz, paciência, benignidade, bondade, fidelidade, mansidão e domínio próprio.',
    reference: 'Gálatas 5:22-23',
  },
  {
    id: 'q18',
    question: 'Quem escreveu a maior parte das epístolas do Novo Testamento?',
    options: ['Pedro', 'João', 'Paulo', 'Tiago'],
    correctIndex: 2,
    category: 'novo_testamento',
    difficulty: 'medio',
    explanation: 'Paulo escreveu 13 das 27 epístolas do Novo Testamento.',
    reference: 'Epístolas Paulinas',
  },
  {
    id: 'q19',
    question: 'Na parábola do Bom Samaritano, quem ajudou o homem ferido?',
    options: ['O sacerdote', 'O levita', 'O samaritano', 'O fariseu'],
    correctIndex: 2,
    category: 'parabolas',
    difficulty: 'facil',
    explanation: 'O samaritano, desprezado pelos judeus, foi quem teve compaixão e ajudou o ferido.',
    reference: 'Lucas 10:33',
  },
  {
    id: 'q20',
    question: 'Qual profeta teve a visão do vale de ossos secos?',
    options: ['Isaías', 'Jeremias', 'Ezequiel', 'Daniel'],
    correctIndex: 2,
    category: 'profetas',
    difficulty: 'medio',
    explanation: 'Ezequiel teve a visão do vale de ossos secos que se levantaram como um exército.',
    reference: 'Ezequiel 37:1-10',
  },
  {
    id: 'q21',
    question: 'Qual cidade Josué conquistou com o som de trombetas?',
    options: ['Jerusalém', 'Jericó', 'Babilônia', 'Nínive'],
    correctIndex: 1,
    category: 'antigo_testamento',
    difficulty: 'medio',
    explanation: 'Os muros de Jericó caíram após os israelitas marcharem por 7 dias tocando trombetas.',
    reference: 'Josué 6:20',
  },
  {
    id: 'q22',
    question: 'Qual o último livro da Bíblia?',
    options: ['Judas', 'Apocalipse', 'Malaquias', 'Atos'],
    correctIndex: 1,
    category: 'novo_testamento',
    difficulty: 'facil',
    explanation: 'Apocalipse é o último livro da Bíblia, escrito pelo apóstolo João.',
    reference: 'Apocalipse 1:1',
  },
  {
    id: 'q23',
    question: 'Quem negou Jesus três vezes?',
    options: ['Judas', 'Tomé', 'Pedro', 'André'],
    correctIndex: 2,
    category: 'personagens',
    difficulty: 'facil',
    explanation: 'Pedro negou conhecer Jesus três vezes antes do galo cantar, como Jesus havia predito.',
    reference: 'Mateus 26:75',
  },
  {
    id: 'q24',
    question: 'Complete: "Tudo posso naquele que..."',
    options: ['...me ama', '...me fortalece', '...me guarda', '...me ensina'],
    correctIndex: 1,
    category: 'versiculos',
    difficulty: 'facil',
    explanation: 'Paulo escreveu esta declaração de fé enquanto estava preso.',
    reference: 'Filipenses 4:13',
  },
  {
    id: 'q25',
    question: 'Quantas pragas Deus enviou sobre o Egito?',
    options: ['7', '10', '12', '5'],
    correctIndex: 1,
    category: 'antigo_testamento',
    difficulty: 'medio',
    explanation: 'Deus enviou 10 pragas sobre o Egito para libertar o povo de Israel da escravidão.',
    reference: 'Êxodo 7-12',
  },
  {
    id: 'q26',
    question: 'Na parábola dos talentos, quantos talentos recebeu o primeiro servo?',
    options: ['1', '2', '5', '10'],
    correctIndex: 2,
    category: 'parabolas',
    difficulty: 'medio',
    explanation: 'O primeiro servo recebeu 5 talentos e os multiplicou, sendo elogiado pelo senhor.',
    reference: 'Mateus 25:15',
  },
  {
    id: 'q27',
    question: 'Qual profeta foi levado ao céu em um carro de fogo?',
    options: ['Elias', 'Eliseu', 'Enoque', 'Moisés'],
    correctIndex: 0,
    category: 'profetas',
    difficulty: 'medio',
    explanation: 'Elias foi arrebatado ao céu em um redemoinho com um carro e cavalos de fogo.',
    reference: '2 Reis 2:11',
  },
  {
    id: 'q28',
    question: 'Quem interpretou os sonhos do Faraó sobre as vacas gordas e magras?',
    options: ['Moisés', 'Daniel', 'José', 'Abraão'],
    correctIndex: 2,
    category: 'personagens',
    difficulty: 'medio',
    explanation: 'José interpretou que haveria 7 anos de fartura seguidos de 7 anos de fome.',
    reference: 'Gênesis 41:25-30',
  },
  {
    id: 'q29',
    question: 'Onde Jesus nasceu?',
    options: ['Nazaré', 'Jerusalém', 'Belém', 'Cafarnaum'],
    correctIndex: 2,
    category: 'novo_testamento',
    difficulty: 'facil',
    explanation: 'Jesus nasceu em Belém da Judéia, como profetizado por Miqueias.',
    reference: 'Mateus 2:1',
  },
  {
    id: 'q30',
    question: 'Qual a montanha onde Moisés recebeu os Dez Mandamentos?',
    options: ['Monte Carmelo', 'Monte Sinai', 'Monte das Oliveiras', 'Monte Sião'],
    correctIndex: 1,
    category: 'antigo_testamento',
    difficulty: 'medio',
    explanation: 'Moisés subiu ao Monte Sinai e recebeu as tábuas da lei com os Dez Mandamentos.',
    reference: 'Êxodo 19:20',
  },
  {
    id: 'q31',
    question: 'Qual foi o primeiro milagre de Jesus?',
    options: ['Curar um cego', 'Multiplicar pães', 'Transformar água em vinho', 'Andar sobre as águas'],
    correctIndex: 2,
    category: 'novo_testamento',
    difficulty: 'medio',
    explanation: 'O primeiro milagre de Jesus foi transformar água em vinho nas bodas de Caná.',
    reference: 'João 2:1-11',
  },
  {
    id: 'q32',
    question: 'Quem traiu Jesus por 30 moedas de prata?',
    options: ['Pedro', 'Judas Iscariotes', 'Tomé', 'Mateus'],
    correctIndex: 1,
    category: 'personagens',
    difficulty: 'facil',
    explanation: 'Judas Iscariotes traiu Jesus com um beijo no jardim do Getsêmani.',
    reference: 'Mateus 26:15',
  },
  {
    id: 'q33',
    question: 'Na visão de Isaías, quantas asas tinham os serafins?',
    options: ['2', '4', '6', '8'],
    correctIndex: 2,
    category: 'profetas',
    difficulty: 'dificil',
    explanation: 'Os serafins tinham 6 asas: 2 cobriam o rosto, 2 cobriam os pés e 2 usavam para voar.',
    reference: 'Isaías 6:2',
  },
  {
    id: 'q34',
    question: 'Complete: "Porque para Deus..."',
    options: ['...tudo é possível', '...nada é impossível', '...há sempre esperança', '...existe uma solução'],
    correctIndex: 1,
    category: 'versiculos',
    difficulty: 'medio',
    explanation: 'O anjo Gabriel disse estas palavras a Maria ao anunciar o nascimento de Jesus.',
    reference: 'Lucas 1:37',
  },
  {
    id: 'q35',
    question: 'Na parábola das 10 virgens, quantas eram prudentes?',
    options: ['3', '5', '7', '10'],
    correctIndex: 1,
    category: 'parabolas',
    difficulty: 'medio',
    explanation: '5 virgens prudentes levaram azeite extra para suas lâmpadas enquanto as 5 néscias não levaram.',
    reference: 'Mateus 25:1-2',
  },
  {
    id: 'q36',
    question: 'Qual era a profissão de Jesus antes do ministério?',
    options: ['Pescador', 'Pastor', 'Carpinteiro', 'Agricultor'],
    correctIndex: 2,
    category: 'novo_testamento',
    difficulty: 'facil',
    explanation: 'Jesus trabalhou como carpinteiro em Nazaré, seguindo a profissão de José.',
    reference: 'Marcos 6:3',
  },
  {
    id: 'q37',
    question: 'Quem foi a primeira mulher mencionada na Bíblia?',
    options: ['Sara', 'Eva', 'Raquel', 'Maria'],
    correctIndex: 1,
    category: 'personagens',
    difficulty: 'facil',
    explanation: 'Eva foi a primeira mulher, criada por Deus a partir da costela de Adão.',
    reference: 'Gênesis 2:22',
  },
  {
    id: 'q38',
    question: 'Qual profeta escreveu sobre o "Servo Sofredor"?',
    options: ['Jeremias', 'Isaías', 'Ezequiel', 'Miqueias'],
    correctIndex: 1,
    category: 'profetas',
    difficulty: 'dificil',
    explanation: 'Isaías 53 profetizou sobre o sofrimento do Messias, cumprido em Jesus Cristo.',
    reference: 'Isaías 53',
  },
  {
    id: 'q39',
    question: 'Quantos dias Lázaro estava morto quando Jesus o ressuscitou?',
    options: ['1 dia', '2 dias', '3 dias', '4 dias'],
    correctIndex: 3,
    category: 'novo_testamento',
    difficulty: 'dificil',
    explanation: 'Lázaro estava morto há 4 dias quando Jesus o chamou para fora do sepulcro.',
    reference: 'João 11:39',
  },
  {
    id: 'q40',
    question: 'Na parábola da ovelha perdida, quantas ovelhas o pastor tinha?',
    options: ['50', '99', '100', '200'],
    correctIndex: 2,
    category: 'parabolas',
    difficulty: 'medio',
    explanation: 'O pastor deixou 99 ovelhas no campo para buscar a 1 que se perdeu.',
    reference: 'Lucas 15:4',
  },
  {
    id: 'q41',
    question: 'Qual rei pediu sabedoria a Deus em vez de riquezas?',
    options: ['Davi', 'Salomão', 'Josias', 'Ezequias'],
    correctIndex: 1,
    category: 'personagens',
    difficulty: 'medio',
    explanation: 'Salomão pediu sabedoria e Deus lhe deu também riquezas e honra.',
    reference: '1 Reis 3:9-12',
  },
  {
    id: 'q42',
    question: 'Complete: "O temor do Senhor é o princípio da..."',
    options: ['...fé', '...sabedoria', '...obediência', '...bênção'],
    correctIndex: 1,
    category: 'versiculos',
    difficulty: 'medio',
    explanation: 'Provérbios ensina que reverenciar a Deus é o início de toda sabedoria verdadeira.',
    reference: 'Provérbios 9:10',
  },
  {
    id: 'q43',
    question: 'Qual apóstolo era cobrador de impostos antes de seguir Jesus?',
    options: ['Pedro', 'João', 'Mateus', 'Filipe'],
    correctIndex: 2,
    category: 'personagens',
    difficulty: 'medio',
    explanation: 'Mateus (também chamado Levi) era cobrador de impostos em Cafarnaum.',
    reference: 'Mateus 9:9',
  },
  {
    id: 'q44',
    question: 'Qual profeta teve que se casar com uma mulher infiel como símbolo?',
    options: ['Amós', 'Oseias', 'Joel', 'Naum'],
    correctIndex: 1,
    category: 'profetas',
    difficulty: 'dificil',
    explanation: 'Deus mandou Oseias casar com Gômer como símbolo do amor de Deus por Israel infiel.',
    reference: 'Oseias 1:2',
  },
  {
    id: 'q45',
    question: 'Em que cidade Paulo se converteu no caminho?',
    options: ['Jerusalém', 'Roma', 'Damasco', 'Antioquia'],
    correctIndex: 2,
    category: 'novo_testamento',
    difficulty: 'medio',
    explanation: 'Saulo (Paulo) estava a caminho de Damasco quando teve o encontro com Jesus ressuscitado.',
    reference: 'Atos 9:3',
  },
  {
    id: 'q46',
    question: 'Qual foi o sinal que Deus deu a Noé após o dilúvio?',
    options: ['Uma estrela', 'O arco-íris', 'Uma pomba', 'O sol'],
    correctIndex: 1,
    category: 'antigo_testamento',
    difficulty: 'facil',
    explanation: 'Deus colocou o arco-íris nas nuvens como sinal da aliança de nunca mais destruir a terra com dilúvio.',
    reference: 'Gênesis 9:13',
  },
  {
    id: 'q47',
    question: 'Qual era o nome do jardim onde Adão e Eva viviam?',
    options: ['Getsêmani', 'Éden', 'Galileia', 'Canaã'],
    correctIndex: 1,
    category: 'antigo_testamento',
    difficulty: 'facil',
    explanation: 'O Jardim do Éden foi o lugar perfeito criado por Deus para Adão e Eva.',
    reference: 'Gênesis 2:8',
  },
  {
    id: 'q48',
    question: 'Quem sonhou com uma escada que chegava ao céu?',
    options: ['Abraão', 'Isaque', 'Jacó', 'José'],
    correctIndex: 2,
    category: 'personagens',
    difficulty: 'medio',
    explanation: 'Jacó sonhou com uma escada com anjos subindo e descendo, e Deus no topo.',
    reference: 'Gênesis 28:12',
  },
  {
    id: 'q49',
    question: 'Na parábola do grão de mostarda, a que Jesus comparou o Reino de Deus?',
    options: ['A uma pérola', 'A um tesouro', 'A uma semente de mostarda', 'A um fermento'],
    correctIndex: 2,
    category: 'parabolas',
    difficulty: 'medio',
    explanation: 'A semente de mostarda é a menor das sementes, mas cresce e se torna a maior das plantas.',
    reference: 'Mateus 13:31-32',
  },
  {
    id: 'q50',
    question: 'Complete: "Ora, a fé é a certeza daquilo que esperamos e a prova das coisas que..."',
    options: ['...Deus prometeu', '...não vemos', '...estão por vir', '...cremos'],
    correctIndex: 1,
    category: 'versiculos',
    difficulty: 'dificil',
    explanation: 'Hebreus 11:1 é a definição bíblica de fé, base de toda caminhada cristã.',
    reference: 'Hebreus 11:1',
  },
];

export function getQuestionsByCategory(category: QuizCategory): QuizQuestion[] {
  return bibleQuizQuestions.filter(q => q.category === category);
}

export function getQuestionsByDifficulty(difficulty: QuizDifficulty): QuizQuestion[] {
  return bibleQuizQuestions.filter(q => q.difficulty === difficulty);
}

export function getRandomQuestions(count: number, category?: QuizCategory): QuizQuestion[] {
  let pool = category
    ? bibleQuizQuestions.filter(q => q.category === category)
    : [...bibleQuizQuestions];
  const shuffled = pool.sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}
