export interface ReadingDay {
  day: number;
  book: string;
  chapters: string;
  summary: string;
}

export interface ReadingMarathon {
  id: string;
  title: string;
  description: string;
  emoji: string;
  totalDays: number;
  category: string;
  days: ReadingDay[];
}

export const readingMarathons: ReadingMarathon[] = [
  {
    id: 'new-testament-90',
    title: 'Novo Testamento em 90 Dias',
    description: 'Leia todo o Novo Testamento em 3 meses, com leituras diárias organizadas.',
    emoji: '📖',
    totalDays: 90,
    category: 'Maratona',
    days: [
      { day: 1, book: 'Mateus', chapters: '1-3', summary: 'Genealogia de Jesus, nascimento e batismo' },
      { day: 2, book: 'Mateus', chapters: '4-6', summary: 'Tentação, início do ministério, Sermão do Monte' },
      { day: 3, book: 'Mateus', chapters: '7-9', summary: 'Sermão do Monte (cont.), milagres de cura' },
      { day: 4, book: 'Mateus', chapters: '10-12', summary: 'Envio dos 12, João Batista, controvérsias' },
      { day: 5, book: 'Mateus', chapters: '13-15', summary: 'Parábolas do Reino, multiplicação dos pães' },
      { day: 6, book: 'Mateus', chapters: '16-18', summary: 'Confissão de Pedro, transfiguração, humildade' },
      { day: 7, book: 'Mateus', chapters: '19-21', summary: 'Casamento, jovem rico, entrada triunfal' },
      { day: 8, book: 'Mateus', chapters: '22-24', summary: 'Parábolas, debates, sinais do fim' },
      { day: 9, book: 'Mateus', chapters: '25-28', summary: 'Parábolas finais, crucificação, ressurreição' },
      { day: 10, book: 'Marcos', chapters: '1-4', summary: 'Início do ministério, parábolas, tempestade' },
      { day: 11, book: 'Marcos', chapters: '5-8', summary: 'Milagres, alimentação dos 5000, confissão' },
      { day: 12, book: 'Marcos', chapters: '9-12', summary: 'Transfiguração, ensinamentos, entrada em Jerusalém' },
      { day: 13, book: 'Marcos', chapters: '13-16', summary: 'Profecias, paixão, morte e ressurreição' },
      { day: 14, book: 'Lucas', chapters: '1-3', summary: 'Nascimento de João e Jesus, genealogia' },
      { day: 15, book: 'Lucas', chapters: '4-6', summary: 'Tentação, ministério na Galileia, Bem-aventuranças' },
      { day: 16, book: 'Lucas', chapters: '7-9', summary: 'Curas, parábolas, missão dos doze' },
      { day: 17, book: 'Lucas', chapters: '10-12', summary: 'Bom Samaritano, oração, alertas' },
      { day: 18, book: 'Lucas', chapters: '13-16', summary: 'Parábolas: filho pródigo, mordomo, Lázaro' },
      { day: 19, book: 'Lucas', chapters: '17-20', summary: 'Fé, gratidão, parábolas, entrada em Jerusalém' },
      { day: 20, book: 'Lucas', chapters: '21-24', summary: 'Profecias, última ceia, crucificação, ressurreição' },
      { day: 21, book: 'João', chapters: '1-3', summary: 'O Verbo, Nicodemos, água viva' },
      { day: 22, book: 'João', chapters: '4-6', summary: 'Samaritana, cura, pão da vida' },
      { day: 23, book: 'João', chapters: '7-9', summary: 'Festa dos tabernáculos, luz do mundo, cego' },
      { day: 24, book: 'João', chapters: '10-12', summary: 'Bom Pastor, Lázaro, entrada triunfal' },
      { day: 25, book: 'João', chapters: '13-15', summary: 'Lava-pés, discurso de despedida, videira' },
      { day: 26, book: 'João', chapters: '16-18', summary: 'Espírito Santo, oração sacerdotal, prisão' },
      { day: 27, book: 'João', chapters: '19-21', summary: 'Crucificação, ressurreição, aparições' },
      { day: 28, book: 'Atos', chapters: '1-3', summary: 'Ascensão, Pentecostes, primeiros sermões' },
      { day: 29, book: 'Atos', chapters: '4-6', summary: 'Perseguição, comunidade, diáconos' },
      { day: 30, book: 'Atos', chapters: '7-9', summary: 'Estêvão, conversão de Saulo' },
      { day: 31, book: 'Atos', chapters: '10-12', summary: 'Cornélio, expansão aos gentios, Pedro preso' },
      { day: 32, book: 'Atos', chapters: '13-15', summary: 'Primeira viagem missionária, concílio' },
      { day: 33, book: 'Atos', chapters: '16-18', summary: 'Segunda viagem missionária, Filipos, Corinto' },
      { day: 34, book: 'Atos', chapters: '19-21', summary: 'Éfeso, terceira viagem, Jerusalém' },
      { day: 35, book: 'Atos', chapters: '22-24', summary: 'Defesa de Paulo, julgamento' },
      { day: 36, book: 'Atos', chapters: '25-28', summary: 'Apelo a César, naufrágio, Roma' },
      { day: 37, book: 'Romanos', chapters: '1-4', summary: 'Pecado universal, justificação pela fé' },
      { day: 38, book: 'Romanos', chapters: '5-8', summary: 'Graça, santificação, vida no Espírito' },
      { day: 39, book: 'Romanos', chapters: '9-12', summary: 'Israel, misericórdia, vida cristã prática' },
      { day: 40, book: 'Romanos', chapters: '13-16', summary: 'Autoridades, amor, saudações' },
      { day: 41, book: '1 Coríntios', chapters: '1-5', summary: 'Divisões, sabedoria de Deus, imoralidade' },
      { day: 42, book: '1 Coríntios', chapters: '6-10', summary: 'Corpo templo, casamento, liberdade' },
      { day: 43, book: '1 Coríntios', chapters: '11-14', summary: 'Ceia do Senhor, dons espirituais, amor' },
      { day: 44, book: '1 Coríntios', chapters: '15-16', summary: 'Ressurreição, instruções finais' },
      { day: 45, book: '2 Coríntios', chapters: '1-6', summary: 'Consolação, ministério da reconciliação' },
      { day: 46, book: '2 Coríntios', chapters: '7-13', summary: 'Generosidade, espinho na carne, despedida' },
      { day: 47, book: 'Gálatas', chapters: '1-6', summary: 'Liberdade em Cristo, fruto do Espírito' },
      { day: 48, book: 'Efésios', chapters: '1-3', summary: 'Bênçãos em Cristo, salvação pela graça' },
      { day: 49, book: 'Efésios', chapters: '4-6', summary: 'Unidade, nova vida, armadura de Deus' },
      { day: 50, book: 'Filipenses', chapters: '1-4', summary: 'Alegria em Cristo, humildade, contentamento' },
      { day: 51, book: 'Colossenses', chapters: '1-4', summary: 'Supremacia de Cristo, vida nova, conselhos' },
      { day: 52, book: '1 Tessalonicenses', chapters: '1-5', summary: 'Fidelidade, volta de Cristo, vigilância' },
      { day: 53, book: '2 Tessalonicenses', chapters: '1-3', summary: 'Dia do Senhor, perseverança' },
      { day: 54, book: '1 Timóteo', chapters: '1-3', summary: 'Instruções pastorais, oração, liderança' },
      { day: 55, book: '1 Timóteo', chapters: '4-6', summary: 'Piedade, viúvas, dinheiro' },
      { day: 56, book: '2 Timóteo', chapters: '1-4', summary: 'Coragem, Escritura inspirada, encargos' },
      { day: 57, book: 'Tito', chapters: '1-3', summary: 'Liderança, graça, boas obras' },
      { day: 58, book: 'Filemom', chapters: '1', summary: 'Carta sobre Onésimo, perdão e reconciliação' },
      { day: 59, book: 'Hebreus', chapters: '1-4', summary: 'Cristo superior aos anjos, descanso de Deus' },
      { day: 60, book: 'Hebreus', chapters: '5-8', summary: 'Sacerdócio de Cristo, nova aliança' },
      { day: 61, book: 'Hebreus', chapters: '9-10', summary: 'Sacrifício perfeito, perseverança' },
      { day: 62, book: 'Hebreus', chapters: '11-13', summary: 'Heróis da fé, disciplina, instruções' },
      { day: 63, book: 'Tiago', chapters: '1-3', summary: 'Provações, fé e obras, língua' },
      { day: 64, book: 'Tiago', chapters: '4-5', summary: 'Humildade, paciência, oração' },
      { day: 65, book: '1 Pedro', chapters: '1-3', summary: 'Esperança viva, conduta, sofrimento' },
      { day: 66, book: '1 Pedro', chapters: '4-5', summary: 'Sofrimento cristão, humildade, firmeza' },
      { day: 67, book: '2 Pedro', chapters: '1-3', summary: 'Crescimento, falsos mestres, dia do Senhor' },
      { day: 68, book: '1 João', chapters: '1-3', summary: 'Luz, amor, filhos de Deus' },
      { day: 69, book: '1 João', chapters: '4-5', summary: 'Amor de Deus, fé vitoriosa' },
      { day: 70, book: '2 João', chapters: '1', summary: 'Verdade e amor, alerta contra engano' },
      { day: 71, book: '3 João', chapters: '1', summary: 'Hospitalidade, Diótrefes, Demétrio' },
      { day: 72, book: 'Judas', chapters: '1', summary: 'Contender pela fé, falsos mestres' },
      { day: 73, book: 'Apocalipse', chapters: '1-3', summary: 'Visão de Cristo, cartas às 7 igrejas' },
      { day: 74, book: 'Apocalipse', chapters: '4-6', summary: 'Trono celestial, cordeiro, selos' },
      { day: 75, book: 'Apocalipse', chapters: '7-9', summary: 'Selados, trombetas, juízos' },
      { day: 76, book: 'Apocalipse', chapters: '10-12', summary: 'Livro aberto, duas testemunhas, dragão' },
      { day: 77, book: 'Apocalipse', chapters: '13-15', summary: 'Besta, 144 mil, taças da ira' },
      { day: 78, book: 'Apocalipse', chapters: '16-18', summary: 'Taças, queda da Babilônia' },
      { day: 79, book: 'Apocalipse', chapters: '19-22', summary: 'Volta de Cristo, juízo, nova Jerusalém' },
      { day: 80, book: 'Revisão', chapters: 'Evangelhos', summary: 'Revise seus destaques de Mateus a João' },
      { day: 81, book: 'Revisão', chapters: 'Atos', summary: 'Revise as lições de Atos dos Apóstolos' },
      { day: 82, book: 'Revisão', chapters: 'Cartas de Paulo (1)', summary: 'Revise Romanos a Efésios' },
      { day: 83, book: 'Revisão', chapters: 'Cartas de Paulo (2)', summary: 'Revise Filipenses a Filemom' },
      { day: 84, book: 'Revisão', chapters: 'Hebreus-Judas', summary: 'Revise Hebreus a Judas' },
      { day: 85, book: 'Revisão', chapters: 'Apocalipse', summary: 'Revise Apocalipse e profecias' },
      { day: 86, book: 'Meditação', chapters: 'Versículos-chave', summary: 'Medite nos seus 5 versículos favoritos' },
      { day: 87, book: 'Meditação', chapters: 'Promessas de Deus', summary: 'Liste e medite nas promessas de Deus' },
      { day: 88, book: 'Meditação', chapters: 'Orações do NT', summary: 'Estude as orações do Novo Testamento' },
      { day: 89, book: 'Aplicação', chapters: 'Vida prática', summary: 'Como aplicar o que aprendeu no dia a dia' },
      { day: 90, book: 'Celebração', chapters: 'Conclusão', summary: 'Celebre! Você completou o Novo Testamento!' },
    ],
  },
  {
    id: 'genesis-30',
    title: 'Gênesis em 30 Dias',
    description: 'Conheça as origens da história da salvação lendo Gênesis capítulo a capítulo.',
    emoji: '🌍',
    totalDays: 30,
    category: 'Maratona',
    days: [
      { day: 1, book: 'Gênesis', chapters: '1-2', summary: 'Criação do mundo e do homem' },
      { day: 2, book: 'Gênesis', chapters: '3-4', summary: 'Queda, Caim e Abel' },
      { day: 3, book: 'Gênesis', chapters: '5-7', summary: 'Genealogias, Noé e o dilúvio' },
      { day: 4, book: 'Gênesis', chapters: '8-10', summary: 'Aliança com Noé, nações' },
      { day: 5, book: 'Gênesis', chapters: '11-12', summary: 'Torre de Babel, chamado de Abraão' },
      { day: 6, book: 'Gênesis', chapters: '13-15', summary: 'Abraão e Ló, aliança de Deus' },
      { day: 7, book: 'Gênesis', chapters: '16-18', summary: 'Hagar, Ismael, visitantes de Abraão' },
      { day: 8, book: 'Gênesis', chapters: '19-20', summary: 'Sodoma e Gomorra, Abraão e Abimeleque' },
      { day: 9, book: 'Gênesis', chapters: '21-23', summary: 'Nascimento de Isaque, sacrifício, Sara' },
      { day: 10, book: 'Gênesis', chapters: '24-25', summary: 'Esposa para Isaque, Esaú e Jacó' },
      { day: 11, book: 'Gênesis', chapters: '26-27', summary: 'Isaque, bênção de Jacó' },
      { day: 12, book: 'Gênesis', chapters: '28-29', summary: 'Sonho de Jacó, Labão, Raquel' },
      { day: 13, book: 'Gênesis', chapters: '30-31', summary: 'Filhos de Jacó, fuga de Labão' },
      { day: 14, book: 'Gênesis', chapters: '32-33', summary: 'Jacó luta com Deus, reencontro com Esaú' },
      { day: 15, book: 'Gênesis', chapters: '34-36', summary: 'Diná, Deus confirma aliança, genealogias' },
      { day: 16, book: 'Gênesis', chapters: '37-38', summary: 'José vendido pelos irmãos, Judá e Tamar' },
      { day: 17, book: 'Gênesis', chapters: '39-40', summary: 'José no Egito, prisão, sonhos' },
      { day: 18, book: 'Gênesis', chapters: '41-42', summary: 'José interpreta sonhos do Faraó, irmãos' },
      { day: 19, book: 'Gênesis', chapters: '43-44', summary: 'Segunda viagem dos irmãos' },
      { day: 20, book: 'Gênesis', chapters: '45-46', summary: 'José se revela, Jacó vai ao Egito' },
      { day: 21, book: 'Gênesis', chapters: '47-48', summary: 'Israel no Egito, bênçãos' },
      { day: 22, book: 'Gênesis', chapters: '49-50', summary: 'Bênçãos de Jacó, morte de José' },
      { day: 23, book: 'Revisão', chapters: '1-11', summary: 'Revise a criação até Babel' },
      { day: 24, book: 'Revisão', chapters: '12-25', summary: 'Revise a história de Abraão e Isaque' },
      { day: 25, book: 'Revisão', chapters: '26-36', summary: 'Revise a história de Jacó' },
      { day: 26, book: 'Revisão', chapters: '37-50', summary: 'Revise a história de José' },
      { day: 27, book: 'Meditação', chapters: 'Promessas', summary: 'Medite nas promessas de Deus em Gênesis' },
      { day: 28, book: 'Meditação', chapters: 'Personagens', summary: 'Reflita sobre os personagens e suas lições' },
      { day: 29, book: 'Aplicação', chapters: 'Vida hoje', summary: 'Como Gênesis se aplica à sua vida hoje' },
      { day: 30, book: 'Celebração', chapters: 'Conclusão', summary: 'Parabéns! Gênesis completo!' },
    ],
  },
  {
    id: 'proverbs-31',
    title: 'Provérbios em 31 Dias',
    description: 'Um capítulo por dia: sabedoria prática para cada dia do mês.',
    emoji: '🧠',
    totalDays: 31,
    category: 'Sabedoria',
    days: Array.from({ length: 31 }, (_, i) => ({
      day: i + 1,
      book: 'Provérbios',
      chapters: `${i + 1}`,
      summary: getProverbsSummary(i + 1),
    })),
  },
];

function getProverbsSummary(chapter: number): string {
  const summaries: Record<number, string> = {
    1: 'Propósito dos Provérbios, sabedoria clama',
    2: 'Benefícios da sabedoria, proteção divina',
    3: 'Confia no Senhor, honra a Deus com teus bens',
    4: 'Caminho da sabedoria, guarda o coração',
    5: 'Alerta contra a imoralidade, fidelidade conjugal',
    6: 'Preguiça, coisas que Deus odeia',
    7: 'Alerta contra a tentação',
    8: 'A sabedoria personificada',
    9: 'Convite da sabedoria e da insensatez',
    10: 'Provérbios de Salomão: justo x ímpio',
    11: 'Honestidade, generosidade, justiça',
    12: 'Disciplina, trabalho, palavras sábias',
    13: 'Instrução, riqueza verdadeira',
    14: 'Sabedoria prática, temor do Senhor',
    15: 'Resposta branda, olhos do Senhor',
    16: 'Planos de Deus, humildade, autocontrole',
    17: 'Amizade verdadeira, coração alegre',
    18: 'Poder das palavras, torre forte',
    19: 'Pobreza, paciência, temor do Senhor',
    20: 'Vinho, preguiça, justiça do rei',
    21: 'Coração do rei, justiça, generosidade',
    22: 'Boa reputação, instrução dos filhos',
    23: 'Cobiça, disciplina, embriaguez',
    24: 'Sabedoria, preguiça, imparcialidade',
    25: 'Provérbios copiados, humildade, domínio próprio',
    26: 'O tolo, preguiçoso, fofoqueiro',
    27: 'Amizade, prudência, cuidado',
    28: 'Justiça, confissão, generosidade',
    29: 'Disciplina, justiça, visão',
    30: 'Palavras de Agur, humildade, observação',
    31: 'Mulher virtuosa, elogio e valor',
  };
  return summaries[chapter] || `Provérbios capítulo ${chapter}`;
}
