export interface QuizQuestion {
  id: string;
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
  difficulty: 'facil' | 'medio' | 'dificil';
  category: string;
}

export const quizQuestions: QuizQuestion[] = [
  {
    id: 'q1',
    question: 'Quantos livros tem a Bíblia?',
    options: ['55', '66', '72', '73'],
    correctIndex: 1,
    explanation: 'A Bíblia protestante tem 66 livros: 39 no Antigo Testamento e 27 no Novo Testamento.',
    difficulty: 'facil',
    category: 'Geral',
  },
  {
    id: 'q2',
    question: 'Quem construiu a arca conforme a ordem de Deus?',
    options: ['Abraão', 'Moisés', 'Noé', 'Davi'],
    correctIndex: 2,
    explanation: 'Noé construiu a arca seguindo as instruções de Deus para salvar sua família e os animais do dilúvio (Gênesis 6-9).',
    difficulty: 'facil',
    category: 'Antigo Testamento',
  },
  {
    id: 'q3',
    question: 'Qual é o menor versículo da Bíblia?',
    options: ['João 3:16', 'João 11:35', 'Gênesis 1:1', 'Salmos 23:1'],
    correctIndex: 1,
    explanation: '"Jesus chorou" (João 11:35) é considerado o menor versículo da Bíblia.',
    difficulty: 'facil',
    category: 'Novo Testamento',
  },
  {
    id: 'q4',
    question: 'Quantos discípulos Jesus escolheu?',
    options: ['7', '10', '12', '15'],
    correctIndex: 2,
    explanation: 'Jesus escolheu 12 discípulos (também chamados apóstolos) para segui-lo e espalhar sua mensagem.',
    difficulty: 'facil',
    category: 'Novo Testamento',
  },
  {
    id: 'q5',
    question: 'Quem foi jogado na cova dos leões?',
    options: ['Jonas', 'Daniel', 'Elias', 'Jeremias'],
    correctIndex: 1,
    explanation: 'Daniel foi jogado na cova dos leões por se recusar a parar de orar a Deus, mas Deus fechou a boca dos leões (Daniel 6).',
    difficulty: 'facil',
    category: 'Antigo Testamento',
  },
  {
    id: 'q6',
    question: 'Qual foi o primeiro milagre de Jesus?',
    options: ['Multiplicação dos pães', 'Transformar água em vinho', 'Andar sobre as águas', 'Curar um cego'],
    correctIndex: 1,
    explanation: 'O primeiro milagre de Jesus foi transformar água em vinho nas bodas de Caná (João 2:1-11).',
    difficulty: 'medio',
    category: 'Novo Testamento',
  },
  {
    id: 'q7',
    question: 'Quem escreveu a maior parte dos Salmos?',
    options: ['Salomão', 'Moisés', 'Davi', 'Asafe'],
    correctIndex: 2,
    explanation: 'Davi escreveu aproximadamente 73 dos 150 Salmos.',
    difficulty: 'medio',
    category: 'Antigo Testamento',
  },
  {
    id: 'q8',
    question: 'Qual apóstolo negou Jesus três vezes?',
    options: ['João', 'Tiago', 'Pedro', 'André'],
    correctIndex: 2,
    explanation: 'Pedro negou conhecer Jesus três vezes antes do galo cantar, conforme Jesus havia profetizado (Mateus 26:69-75).',
    difficulty: 'facil',
    category: 'Novo Testamento',
  },
  {
    id: 'q9',
    question: 'Quantos dias e noites Jesus ficou no deserto sendo tentado?',
    options: ['7', '21', '30', '40'],
    correctIndex: 3,
    explanation: 'Jesus ficou 40 dias e 40 noites no deserto sendo tentado pelo diabo (Mateus 4:1-11).',
    difficulty: 'medio',
    category: 'Novo Testamento',
  },
  {
    id: 'q10',
    question: 'Qual é o último livro da Bíblia?',
    options: ['Judas', 'Apocalipse', 'Malaquias', '3 João'],
    correctIndex: 1,
    explanation: 'Apocalipse (ou Revelação) é o último livro da Bíblia, escrito pelo apóstolo João.',
    difficulty: 'facil',
    category: 'Geral',
  },
  {
    id: 'q11',
    question: 'Quem foi o homem mais velho da Bíblia?',
    options: ['Noé', 'Adão', 'Matusalém', 'Enoque'],
    correctIndex: 2,
    explanation: 'Matusalém viveu 969 anos, sendo o homem mais longevo registrado na Bíblia (Gênesis 5:27).',
    difficulty: 'medio',
    category: 'Antigo Testamento',
  },
  {
    id: 'q12',
    question: 'Em qual monte Moisés recebeu os Dez Mandamentos?',
    options: ['Monte Carmelo', 'Monte das Oliveiras', 'Monte Sinai', 'Monte Sião'],
    correctIndex: 2,
    explanation: 'Moisés recebeu os Dez Mandamentos no Monte Sinai (Êxodo 19-20).',
    difficulty: 'medio',
    category: 'Antigo Testamento',
  },
  {
    id: 'q13',
    question: 'Qual foi a praga final que Deus enviou sobre o Egito?',
    options: ['Trevas', 'Gafanhotos', 'Morte dos primogênitos', 'Chuva de granizo'],
    correctIndex: 2,
    explanation: 'A décima e última praga foi a morte dos primogênitos do Egito (Êxodo 12:29-30).',
    difficulty: 'medio',
    category: 'Antigo Testamento',
  },
  {
    id: 'q14',
    question: 'Quem batizou Jesus?',
    options: ['Pedro', 'João Batista', 'Tiago', 'André'],
    correctIndex: 1,
    explanation: 'João Batista batizou Jesus no rio Jordão (Mateus 3:13-17).',
    difficulty: 'facil',
    category: 'Novo Testamento',
  },
  {
    id: 'q15',
    question: 'Qual fruto Eva comeu no Jardim do Éden?',
    options: ['Maçã', 'Figo', 'Uva', 'A Bíblia não especifica'],
    correctIndex: 3,
    explanation: 'A Bíblia não especifica qual fruto era. Diz apenas "fruto da árvore do conhecimento do bem e do mal" (Gênesis 3:6).',
    difficulty: 'dificil',
    category: 'Antigo Testamento',
  },
  {
    id: 'q16',
    question: 'Quantos pães e peixes Jesus usou para alimentar 5.000 pessoas?',
    options: ['3 pães e 2 peixes', '5 pães e 2 peixes', '7 pães e 3 peixes', '5 pães e 5 peixes'],
    correctIndex: 1,
    explanation: 'Jesus multiplicou 5 pães e 2 peixes para alimentar cerca de 5.000 homens (Mateus 14:17-21).',
    difficulty: 'medio',
    category: 'Novo Testamento',
  },
  {
    id: 'q17',
    question: 'Quem interpretou os sonhos do Faraó?',
    options: ['Moisés', 'Daniel', 'José', 'Salomão'],
    correctIndex: 2,
    explanation: 'José interpretou os sonhos do Faraó sobre 7 anos de fartura e 7 anos de fome (Gênesis 41).',
    difficulty: 'medio',
    category: 'Antigo Testamento',
  },
  {
    id: 'q18',
    question: 'Qual livro da Bíblia é conhecido como o "Livro da Sabedoria"?',
    options: ['Salmos', 'Eclesiastes', 'Provérbios', 'Cantares'],
    correctIndex: 2,
    explanation: 'Provérbios é conhecido como o livro da sabedoria, escrito principalmente por Salomão.',
    difficulty: 'medio',
    category: 'Geral',
  },
  {
    id: 'q19',
    question: 'Onde Jesus nasceu?',
    options: ['Nazaré', 'Jerusalém', 'Belém', 'Cafarnaum'],
    correctIndex: 2,
    explanation: 'Jesus nasceu em Belém da Judeia, conforme as profecias (Mateus 2:1).',
    difficulty: 'facil',
    category: 'Novo Testamento',
  },
  {
    id: 'q20',
    question: 'Quem traiu Jesus por 30 moedas de prata?',
    options: ['Pedro', 'Tomé', 'Judas Iscariotes', 'Bartolomeu'],
    correctIndex: 2,
    explanation: 'Judas Iscariotes traiu Jesus por 30 moedas de prata (Mateus 26:14-16).',
    difficulty: 'facil',
    category: 'Novo Testamento',
  },
];
